name: Fairy

on:
  schedule:
    - cron: '30 6 * * *'  # 6:30 AM IST (noon UTC)
    - cron: '30 8 * * *'  # 8:30 AM IST (2 PM UTC)
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16

      # Runs a single command using the runners shell
      - name: Run commit script
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git commit --allow-empty -m "Plant grass: `date +'%Y-%m-%d %H:%M:%S'`"
          git push origin main
