name: Bazoomba commit

on:
  schedule:
    - cron: '20 12 * * *'  # 6:20 PM IST (12:45 PM UTC)
    - cron: '30 6 * * *'  # 6:30 AM IST (12:00 AM UTC, the next day)
    - cron: '30 8 * * *'  # 8:30 AM IST (2:00 AM UTC, the next day)
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  commit-615pm:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0  # Fetch the entire commit history for proper commits

      - name: Set Git Config
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Make Changes
        run: |
          # Perform your automated changes here
          echo "Auto commit content (6:20 PM IST): $(date +'%Y-%m-%d %H:%M:%S')" >> example_file.txt

      - name: Check for Changes
        run: |
          # Check if there are any changes to commit
          git diff-index --quiet HEAD || git commit -am "Auto commit by ${GITHUB_ACTOR} (6:20 PM IST): $(date +'%Y-%m-%d %H:%M:%S')"
          
      - name: Push Changes
        run: |
          # Push the changes to the main branch
          git push origin main
